name: Build

on:
  push:
    branches:
      - new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Gradle cache for faster builds
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      # - run: flutter analyze .

      # Run widget tests for our flutter project.
      # - run: flutter test

      # Build apk.
      - run: flutter build apk --release

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      # - name: Commit on Telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     format: markdown
      #     disable_web_page_preview: true
      #     message: |
      #       New commit pushed to [${{ github.event.repository.name }}](${{ github.event.repository.html_url }}) by [${{ github.event.head_commit.author.name }}](${{ github.event.head_commit.author.html_url }}).
      #       Commit message: ${{ github.event.head_commit.message }}
